#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# that default yellow colour burns my eyes I swear...
bspc config presel_feedback_color \#808080

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
